
eureka:
# enableSelfPreservation: false
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka2:8672/eureka/,http://eureka3:8673/eureka/
server:
  port: 8671



