
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_server:http://localhost:8761/eureka/}
server:
  port: 8801
election:
  dataPath: /logs/data/
  groupId: cloudin_arrange
  serverIdStr: ${server_id:127.0.0.1:9672}
  initialConfStr: ${server_cluster:127.0.0.1:9671,127.0.0.1:9672}


